# action.yml
name: 'subwasm'
description: 'Subwasm wrapper'
inputs:
  subwasm-cmd:  # id of input
    description: 'subwasm command'
    required: true
    default: 'subwasm help'
  working-directory:
    description: 'default work dir'
    required: true
    default: '.'
runs:
  using: 'docker'
  image: 'docker://openactionrs/subwasm:0.0.1-dev002'
  args:
    - ${{inputs.working-directory}}
    - ${{inputs.subwasm-cmd}}
