name: Release

on:
  push:
    branches:
      - master
    tags:
      - "[0-9].*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare tools
        uses: open-actions-rs/subwasm@master
        with:
          subwasm-cmd: 'help'
      - name: list
        run: cat SUBWASM.out >BODY
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          prerelease: true
          generate_release_notes: true
          body_path: BODY 

